\makeatletter
\renewcommand{\lst@MakeCaption}[1]{
  \lst@ifdisplaystyle
  \ifx #1t%
  \ifx\lst@@caption\@empty\expandafter\lst@HRefStepCounter \else
  \expandafter\refstepcounter
  \fi {lstlisting}%
  \ifx\lst@label\@empty\else \label{\lst@label}\fi
  \let\lst@arg\lst@intname \lst@ReplaceIn\lst@arg\lst@filenamerpl
  \global\let\lst@name\lst@arg \global\let\lstname\lst@name
  \lst@ifnolol\else
  \ifx\lst@@caption\@empty
  \ifx\lst@caption\@empty
  \ifx\lst@intname\@empty \else \def\lst@temp{ }%
  \ifx\lst@intname\lst@temp \else
  \addcontentsline{lol}{lstlisting}\lst@name
  \fi\fi
  \fi
  \else
  \addcontentsline{lol}{lstlisting}%
  {\protect\numberline{\thelstlisting}\lst@@caption}%
  \fi
  \fi
  \fi
  \ifx\lst@caption\@empty\else
  \lst@IfSubstring #1\lst@captionpos
  {\begingroup \let\@@vskip\vskip
    \def\vskip{\afterassignment\lst@vskip \@tempskipa}%
    \def\lst@vskip{\nobreak\@@vskip\@tempskipa\nobreak}%
    \par\@parboxrestore\normalsize\normalfont % \noindent (AS)
    \ifx #1t\allowbreak \fi
    \ifx\lst@title\@empty
    \settoheight{\mp@capht}%
    {\parbox[b]{.9\mp@margwd}{\raggedleft\sffamily\slshape\small%
        \lst@makecaption\fnum@lstlisting\lst@caption}}%

    \hspace{-\mp@margwd}%
    \vspace{-\mp@capht}%
    \parbox[t]{.9\mp@margwd}{\raggedleft\sffamily\slshape\small%
      \lst@makecaption\fnum@lstlisting\lst@caption}%

    % \lst@makecaption\fnum@lstlisting\lst@caption % (AS)
    \else
    \lst@maketitle\lst@title % (AS)
    \fi
    \ifx #1b\allowbreak \fi
    \endgroup}{}%
  \fi
  \fi
}
\makeatother
